<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML and DL</b></center>

<center><b><h1>Lab - 6</b></center>    
<pre>    

# Decision Tree Classifier

In [1]:
from sklearn.datasets import load_iris 

# Import iris data ser using sklearn

In [3]:
df = load_iris()

In [30]:
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

# Importing the libraries

In [7]:
import numpy as np
import pandas as pd

# Divide the data into input and output

In [9]:
input=df.data

In [11]:
input

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [26]:
output=df.target

In [28]:
output

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Splitting the dataset into the Training set and Test set

In [38]:
from sklearn.model_selection import train_test_split

In [47]:
X_train,X_test,y_train,y_test = train_test_split(input,output,random_state=44,train_size=0.8)

In [54]:
X_train.shape

(120, 4)

In [58]:
y_train.shape

(120,)

# Fitting DecisionTreeClassifier   on dataset

In [87]:
from sklearn.tree import DecisionTreeClassifier

In [89]:
model=DecisionTreeClassifier()

In [96]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

# Display Decision Tree

In [98]:
%matplotlib qt

In [102]:
from sklearn import tree

In [104]:
tree.plot_tree(model)

[Text(0.4, 0.9285714285714286, 'x[2] <= 2.6\ngini = 0.666\nsamples = 120\nvalue = [41, 41, 38]'),
 Text(0.3, 0.7857142857142857, 'gini = 0.0\nsamples = 41\nvalue = [41, 0, 0]'),
 Text(0.35, 0.8571428571428572, 'True  '),
 Text(0.5, 0.7857142857142857, 'x[2] <= 4.75\ngini = 0.499\nsamples = 79\nvalue = [0, 41, 38]'),
 Text(0.45, 0.8571428571428572, '  False'),
 Text(0.4, 0.6428571428571429, 'gini = 0.0\nsamples = 37\nvalue = [0, 37, 0]'),
 Text(0.6, 0.6428571428571429, 'x[3] <= 1.75\ngini = 0.172\nsamples = 42\nvalue = [0, 4, 38]'),
 Text(0.4, 0.5, 'x[3] <= 1.65\ngini = 0.5\nsamples = 6\nvalue = [0, 3, 3]'),
 Text(0.3, 0.35714285714285715, 'x[1] <= 2.75\ngini = 0.48\nsamples = 5\nvalue = [0, 2, 3]'),
 Text(0.2, 0.21428571428571427, 'x[1] <= 2.35\ngini = 0.444\nsamples = 3\nvalue = [0, 2, 1]'),
 Text(0.1, 0.07142857142857142, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.3, 0.07142857142857142, 'gini = 0.0\nsamples = 2\nvalue = [0, 2, 0]'),
 Text(0.4, 0.21428571428571427, 'gini 

# Predict the x_test 

In [106]:
model.predict(X_test)

array([2, 0, 1, 1, 2, 0, 2, 2, 2, 1, 0, 2, 0, 2, 0, 0, 2, 1, 0, 2, 1, 1,
       2, 1, 2, 1, 0, 1, 0, 2])

In [108]:
model.score(X_test,y_test)

0.8666666666666667

# Import diabetes.csv dataset 

In [126]:
df1=pd.read_csv('diabetes.csv')

In [128]:
df1

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Check the distribution of the target

In [130]:
df1['Outcome'].value_counts()

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64

# Replace zeros with NaN for specific columns

In [147]:
df2=df1.copy()

In [158]:
cols=['Glucose','BMI','BloodPressure','SkinThickness','Insulin']
df2[cols]=df2[cols].replace(0,np.nan)

# Check for missing values

# Fill missing values with median

In [145]:
df1.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

# Visualize Distributions

# Convert Targer data into interger code

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin   BMI  \
0              6    148.0           72.0       35.00000  155.548223  33.6   
1              1     85.0           66.0       29.00000  155.548223  26.6   
2              8    183.0           64.0       29.15342  155.548223  23.3   
3              1     89.0           66.0       23.00000   94.000000  28.1   
4              0    137.0           40.0       35.00000  168.000000  43.1   
..           ...      ...            ...            ...         ...   ...   
763           10    101.0           76.0       48.00000  180.000000  32.9   
764            2    122.0           70.0       27.00000  155.548223  36.8   
765            5    121.0           72.0       23.00000  112.000000  26.2   
766            1    126.0           60.0       29.15342  155.548223  30.1   
767            1     93.0           70.0       31.00000  155.548223  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50      NaN  
1                       0.351   31      NaN  
2                       0.672   32      NaN  
3                       0.167   21      NaN  
4                       2.288   33      NaN  
..                        ...  ...      ...  
763                     0.171   63      NaN  
764                     0.340   27      NaN  
765                     0.245   30      NaN  
766                     0.349   47      NaN  
767                     0.315   23      NaN  

[768 rows x 9 columns]

# Divide the data into input and output

# Splitting the dataset into the Training set and Test set

# Create Model

# Fitting DecisionTreeClassifier   on dataset

# Display Decision Tree

# Predict the x_test 

# Display Training Accuracy

# Display Test Accuracy

# Confusion Matrix

# Save Model State

In [112]:
import pickle

In [114]:
with open('model.pkl','wb') as file:
    pickle.dump(model,file)

# Load Model from Disk

In [117]:
with open('model.pkl','rb') as file:
    loaded_model = pickle.load(file)

In [121]:
loaded_model.predict(X_test)

array([2, 0, 1, 1, 2, 0, 2, 2, 2, 1, 0, 2, 0, 2, 0, 0, 2, 1, 0, 2, 1, 1,
       2, 1, 2, 1, 0, 1, 0, 2])